# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_SOC_EXYNOS7885) := \
	      exynos7885.dtb 
dtbo-$(CONFIG_MACH_EXYNOS7904_MK) := \
        exynos7904-a30_swa_open_00.dtbo \
        exynos7904-a30_swa_open_01.dtbo \
        exynos7904-a30_swa_open_02.dtbo
always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
